eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
spring:
  application:
    name: DIS_8088
server:
  port: 8088

userinfo:
  password: 123456789
  username: huangfazhou
